services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=bart.deboeck@xenopz.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - internal

  server:
    image: cortezaproject/corteza:${VERSION}
    env_file:
      - .env
    networks:
      - internal
    labels:
      - "traefik.http.routers.server.rule=Host(`corteza.xenopz.com`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
    volumes:
      - "./data/server:/data"
    restart: on-failure

  es:
    image: opensearchproject/opensearch:1.3.0
    restart: on-failure
    networks:
      - internal
    environment:
      - cluster.name=es-docker-cluster
      - node.name=es
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    volumes:
      - ./data/es:/usr/share/elasticsearch/data

  discovery:
    image: cortezaproject/corteza-server-discovery:${VERSION}
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - es
      - server
    networks:
      - internal
    environment:
      VIRTUAL_HOST: discovery.${DOMAIN}
      VIRTUAL_PORT: 80

networks:
  internal: {}
